---
- hosts: client
  become: true
  environment:
    Website_Name: "Ansible-Nginx"
    Nginx_user: "nginx"
    Nginx_group: "nginx"
    Nginx_port: "80"
    content: "Ansible-Nginx"

  roles:
    - {role: Redhat_Install, when: ansible_os_family  == 'Redhat'}
    - {role: Debian_Install, when: ansible_os_family  == 'Debian' or ansible_os_family == 'Ubuntu'}
  
  post_tasks:
    - name: Testing NGINX conf
      command: "/usr/local/nginx -t -C /etc/nginx/conf.d/default.conf"
      register: rs_config

    - name: print result
      debug:
        msg: "{{ rs_config.stdout_lines }}"
