---
- hosts: client
  become: true
  environment:
    System_OS: "{{ ansible_os_family }}"
    Nginx_port: 80

  roles:
    - {role: Redhat_Install, when: System_OS == 'Redhat'}
    - {role: Debian_Install, when: System_OS == 'Debian'}
