- hosts: client
  remote_user: root
  become: true
  vars:
    Website_Name: "Ansible-Nginx"
    Nginx_user: "nginx"
    Nginx_group: "nginx"
    Nginx_port: "80"
    Nginx_logpath: "/var/log/nginx/access.log"
    content: "Ansible-Nginx"

  roles:
    - {role: Redhat_Install, when: ansible_os_family  == 'RedHat'}
    - {role: Debian_Install, when: ansible_os_family  == 'Debian' or ansible_os_family == 'Ubuntu'}
  
  handlers:
  - name: restart service
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - nginx
      - php-fpm
  
  - name: reload Nginx service
    service:
      name: nginx
      state: reloaded

  - name: reload php-fpm service
    service: 
      name: php-fpm
      state: reloaded
