- name: Install Nginx repo
  apt_repository: 
    repo: 'deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} nginx'
    state: present

- name: Install Nginx, php, php-fpm
  apt: 
    name: ['nginx', 'php', 'php-fpm']
    state: present
  notify: restart service

- name: Start service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - php-fpm
  
- name: Config Nginx default.conf
  template:
    src: 'template/default.conf.j2'
    dest: '/etc/nginx/conf.d/default.conf'
    mode: '0755'
  notify: reload Nginx service

- name: Config Nginx nginx.conf
  template:
    src: 'template/nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    mode: '0755'
    #validate: '/usr/sbin/nginx -t -c %s'
  notify: reload Nginx service

- name: Config php-fpm
  template:
    src: 'template/www.conf.j2'
    dest: '/etc/php-fpm.d/www.conf'
    mode: '0755'
  with_items:
    - { src: 'template/index.php.j2', dest: '/usr/share/nginx/html/index.php' }
  notify: reload php-fpm service
  
- name: PHP index.php file
  template:
    src: 'template/index.php.j2'
    dest: '/usr/share/nginx/html/index.php'
    mode: '0755'

- name: setting firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
