- name: Install Nginx repo
  yum: 
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: present

- name: Install Nginx, php, php-fpm
  yum: 
    name: {{ item }}
    state: present
  with_items:
    - nginx
    - php
    - php-fpm
  notify: restart service
  
- name: Create website directory
  file:
    path: {{ Nginx_rootpath }}
    state: directory
    mode: '0755'
  
- name: Config Nginx
  template:
    src: 'template/default.conf.j2'
    dest: '/etc/nginx/conf.d/default.conf'
    mode: '0755'
    validate: '/usr/nginx/sbin/nginx -t -c %s'
  notify: reload Nginx service

- name: Config php-fpm
  template:
    src: 'template/www.conf.j2'
    dest: '/etc/php-fpm.d/www.conf'
    mode: '0755'
  with_items:
    - { src: 'template/index.php.j2', dest: '{{ Nginx_rootpath }}/index.php' }
  notify: reload php-fpm service
  
- name: PHP index.php file
  template:
    src: 'template/index.php.j2'
    dest: '{{ Nginx_rootpath }}/index.php'
    mode: '0755'

- name: setting firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp

handlers:
  - name: restart Nginx service
    service: 
      name: nginx
      state: restarted
  
  - name: restart php-fpm service
    service: 
      name: php-fpm
      state: restarted
